---
- hosts: all
  tasks:
  - name: Add Host in Zabbix Server
    zabbix_host:
      server_url: http://52.172.210.250/zabbix/
      login_user: admin
      login_password: zabbix
      host_name: "{{ hostname }}"
      visible_name: "{{ visible }}"
      host_groups:
      - "{{ grp }}"
      link_templates:
      - "{{ templates }}"
      status: enabled
      state: present
      inventory_mode: automatic
      interfaces:
      - type: "{{ type }}"
        main: 1
        useip: 1
        dns: ""
        ip: "{{ ip }}"
        port: "{{ port }}" 

  - name: Slack Notification For Adding Host in Zabbix
    slack:
      token: T5P0QEGFQ/B6H0FG96U/yKczessxOtbB31VGv2VWkncE
      domain: https://prodevans-forge.slack.com
      msg: "{{ hostname }} is added in Zabbix Server"

